# Generated by Django 5.1.6 on 2025-08-10 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_es', models.CharField(db_index=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_es', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('name_es', models.CharField(db_index=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('slug_en', models.SlugField(max_length=200, null=True)),
                ('slug_es', models.SlugField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'indexes': [models.Index(fields=['-created'], name='shop_produc_created_ef211c_idx')],
            },
        ),
    ]
